version: "3"
services:
  plex:
    image: "linuxserver/plex"
    restart: "unless-stopped"
    network_mode: "host"
    environment:
        PUID: 1000
        PGID: 1001
        VERSION: "docker"
    volumes:
      - "/storage/media:/data:ro"
      - "/storage/transcode:/transcode"
      - "/home/abrar/docker/plex/config:/config"  

  # pihole:
  #   image: "pihole/pihole"
  #   restart: "unless-stopped"
  #   ports:
  #     - "53:53/tcp"
  #     - "53:53/udp"
  #     - "67:67/udp"
  #   environment:
  #     TZ: "America/Los_Angeles"
  #     DNS1: "8.8.8.8"
  #     VIRTUAL_HOST: "pihole.hnxlabs.com"
  #     WEBPASSWORD: ""
  #   volumes:
  #     - "/home/abrar/docker/pihole:/etc/pihole"
  #     - "/home/abrar/docker/pihole/dnsmasq.d:/etc/dnsmasq.d"
  #   dns:
  #     - 127.0.0.1
  #     - 8.8.8.8
  #   extra_hosts:
  #     - "plex.hnxlabs.com:192.168.1.65"

  haproxy:
    image: 'haproxy:alpine'
    restart: "unless-stopped"
    depends_on:
      - plex
      - transmission
      - handbrake
    volumes:
      - "/home/abrar/myubuntu/docker/configs/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
      - "/home/abrar/docker/letsencrypt/etc/letsencrypt/live:/ssl:ro"
    ports:
      - "443:443"
      - "4434:4434"

  letsencrypt:
    image: "linuxserver/letsencrypt"
    restart: "unless-stopped"
    environment:
      PUID: 1000
      PGID: 1001
      TZ: "America/Los_angeles"
      URL: "hnxlabs.com"
      SUBDOMAINS: "plex,bt,hb"
      VALIDATION: "http"
      STAGING: "false"
      ONLY_SUBDOMAINS: "true"
    volumes:
      - "/home/abrar/docker/letsencrypt:/config"
    ports:
      - "80:80"
      
  transmission:
    image: "haugene/transmission-openvpn"
    restart: "unless-stopped"
    volumes:
      - "/storage/media:/media"
      - "/etc/localtime:/etc/localtime:ro"
    env_file:
      - "transmission.env"
    cap_add:
      - NET_ADMIN
  
  handbrake:
    image: "jlesage/handbrake"
    restart: "unless-stopped"
    environment:
      USER_ID: 1000
      GROUP_ID: 1001
      TZ: "America/Los_Angeles"
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - "/home/abrar/docker/handbrake:/config:rw"
      - "/storage/media:/storage:ro"
      - "/storage/transcode/handbrake:/output:rw"
