version: "3"
services:
  plex:
    image: "linuxserver/plex"
    restart: "unless-stopped"
    network_mode: "host"
    environment:
        PUID: 1000
        PGID: 1001
        VERSION: "docker"
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - "/mnt/external/media:/data:ro"
      - "/mnt/external/transcode:/transcode"
      - "/mnt/external/docker-mounts/plex/config:/config"
      - "/mnt/external/docker-mounts/letsencrypt/etc/letsencrypt/live:/ssl:ro"

  # pihole:
  #   image: "pihole/pihole"
  #   restart: "unless-stopped"
  #   ports:
  #     - "53:53/tcp"
  #     - "53:53/udp"
  #     - "67:67/udp"
  #   environment:
  #     TZ: "America/Los_Angeles"
  #     DNS1: "8.8.8.8"
  #     VIRTUAL_HOST: "pihole.hnxlabs.com"
  #     WEBPASSWORD: ""
  #   volumes:
  #     - "/mnt/external/docker-mount/pihole:/etc/pihole"
  #     - "/mnt/external/docker-mount/pihole/dnsmasq.d:/etc/dnsmasq.d"
  #   dns:
  #     - 127.0.0.1
  #     - 8.8.8.8
  #   extra_hosts:
  #     - "plex.hnxlabs.com:192.168.1.65"

  haproxy:
    image: 'haproxy:alpine'
    restart: "unless-stopped"
    networks: 
      - media_nw
    depends_on:
      - plex
      - transmission
      - handbrake
    volumes:
      - "/mnt/external/projects/docker/configs/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
      - "/mnt/external/docker-mounts/letsencrypt/etc/letsencrypt/live:/ssl:ro"
    ports:
      - "443:443"

  letsencrypt:
    image: "linuxserver/letsencrypt"
    restart: "unless-stopped"
    networks: 
      - media_nw
    environment:
      PUID: 1000
      PGID: 1001
      TZ: "America/Los_angeles"
      URL: "hnxlabs.com"
      SUBDOMAINS: "plex,bt,hb"
      VALIDATION: "http"
      STAGING: "false"
      ONLY_SUBDOMAINS: "true"
    volumes:
      - "/mnt/external/docker-mounts/letsencrypt:/config"
    ports:
      - "80:80"
      
  transmission:
    image: "linuxserver/transmission"
    restart: "unless-stopped"
    networks: 
      - media_nw
    volumes:
      - "/mnt/external/media:/downloads"
    environment:
      PUID: 1000
      PGID: 1001
      TZ: "America/Los_angeles"
      TRANSMISSION_RPC_HOST_WHITELIST: "bt.hnxlabs.com"
      TRANSMISSION_RPC_HOST_WHITELIST_ENABLED: "true"
    ports:
      - "9091:9091"
  
  handbrake:
    image: "jlesage/handbrake"
    restart: "unless-stopped"
    networks: 
      - media_nw
    environment:
      USER_ID: 1000
      GROUP_ID: 1001
      TZ: "America/Los_Angeles"
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - "/mnt/external/docker-mounts/handbrake:/config:rw"
      - "/mnt/external/media:/data:ro"
      - "/mnt/external/transcode/handbrake:/output:rw"
    ports:
      - "5800:5800"
  
  tautuli:
    image: "tautulli/tautulli"
    restart: "unless-stopped"
    networks: 
      - media_nw
    environment:
        PUID: 1000
        PGID: 1001
        TZ: "America/Los_Angeles"
    volumes:
      - "/mnt/external/docker-mounts/tautuli/config:/config"
      - "/mnt/external/docker-mounts/plex/config/Library/Application Support/Plex Media Server/Logs:/plex_logs:ro"
    ports:
      - "8181:8181"